CC = g++
LIB = -l sqlite3

all: scfbctrl scftptxtctrl scmailctrl scskypectrl scsmsctrl sctwctrl

scfbctrl:
	$(CC) fbctrl.cpp $(LIB) -o scfbctrl
scftptxtctrl:
	$(CC) ftptxtctrl.cpp $(LIB) -o scftptxtctrl
scmailctrl:
	$(CC) mailctrl.cpp $(LIB) -o scmailctrl
scskypectrl:
	$(CC) skypectrl.cpp $(LIB) -o scskypectrl
scsmsctrl:
	$(CC) smsctrl.cpp $(LIB) -o scsmsctrl
sctwctrl:
	$(CC) twctrl.cpp $(LIB) -o sctwctrl